---@meta _

---@class KeyboardInputName

---The KeyboardChip allows you to control your gadgets using your computer's real keyboard.
---@class KeyboardChip:Module
---@field Type "KeyboardChip"
---@field GetButton fun(self:KeyboardChip, name:KeyboardInputName):InputSource Returns an InputSource for a given key.
---@field GetButtonAxis fun(self:KeyboardChip, negativeName:KeyboardInputName, positiveName:KeyboardInputName):InputSource Returns an InputSource axis controlled by two given keys, one for negative and one for positive values.

---Triggered when a key is pressed or released.
---@class KeyboardChipEvent
---@field ButtonDown boolean is `true` if a key was pressed at this event.
---@field ButtonUp boolean if a key was released at this event.
---@field InputName KeyboardInputName returns the input name of the key that triggered this event.
---@field Type "KeyboardChipEvent" is "KeyboardChipEvent"

---@package
---@return KeyboardInputName
function __new_input_name_keyboard__() end

KeyboardChip = {
    Return = __new_input_name_keyboard__(),
    Space = __new_input_name_keyboard__(),
    LeftArrow = __new_input_name_keyboard__(),
    RightArrow = __new_input_name_keyboard__(),
    DownArrow = __new_input_name_keyboard__(),
    UpArrow = __new_input_name_keyboard__(),
    Backspace = __new_input_name_keyboard__(),
    Escape = __new_input_name_keyboard__(),
    Tab = __new_input_name_keyboard__(),
    Clear = __new_input_name_keyboard__(),
    Pause = __new_input_name_keyboard__(),
    Exclaim = __new_input_name_keyboard__(),
    DoubleQuote = __new_input_name_keyboard__(),
    Hash = __new_input_name_keyboard__(),
    Dollar = __new_input_name_keyboard__(),
    Percent = __new_input_name_keyboard__(),
    Ampersand = __new_input_name_keyboard__(),
    Quote = __new_input_name_keyboard__(),
    LeftParen = __new_input_name_keyboard__(),
    RightParen = __new_input_name_keyboard__(),
    Asterisk = __new_input_name_keyboard__(),
    Plus = __new_input_name_keyboard__(),
    Comma = __new_input_name_keyboard__(),
    Minus = __new_input_name_keyboard__(),
    Period = __new_input_name_keyboard__(),
    Slash = __new_input_name_keyboard__(),
    Alpha0 = __new_input_name_keyboard__(),
    Alpha1 = __new_input_name_keyboard__(),
    Alpha2 = __new_input_name_keyboard__(),
    Alpha3 = __new_input_name_keyboard__(),
    Alpha4 = __new_input_name_keyboard__(),
    Alpha5 = __new_input_name_keyboard__(),
    Alpha6 = __new_input_name_keyboard__(),
    Alpha7 = __new_input_name_keyboard__(),
    Alpha8 = __new_input_name_keyboard__(),
    Alpha9 = __new_input_name_keyboard__(),
    Colon = __new_input_name_keyboard__(),
    Semicolon = __new_input_name_keyboard__(),
    Less = __new_input_name_keyboard__(),
    Equals = __new_input_name_keyboard__(),
    Greater = __new_input_name_keyboard__(),
    Question = __new_input_name_keyboard__(),
    At = __new_input_name_keyboard__(),
    LeftBracket = __new_input_name_keyboard__(),
    Backslash = __new_input_name_keyboard__(),
    RightBracket = __new_input_name_keyboard__(),
    Caret = __new_input_name_keyboard__(),
    Underscore = __new_input_name_keyboard__(),
    BackQuote = __new_input_name_keyboard__(),
    A = __new_input_name_keyboard__(),
    B = __new_input_name_keyboard__(),
    C = __new_input_name_keyboard__(),
    D = __new_input_name_keyboard__(),
    E = __new_input_name_keyboard__(),
    F = __new_input_name_keyboard__(),
    G = __new_input_name_keyboard__(),
    H = __new_input_name_keyboard__(),
    I = __new_input_name_keyboard__(),
    J = __new_input_name_keyboard__(),
    K = __new_input_name_keyboard__(),
    L = __new_input_name_keyboard__(),
    M = __new_input_name_keyboard__(),
    N = __new_input_name_keyboard__(),
    O = __new_input_name_keyboard__(),
    P = __new_input_name_keyboard__(),
    Q = __new_input_name_keyboard__(),
    R = __new_input_name_keyboard__(),
    S = __new_input_name_keyboard__(),
    T = __new_input_name_keyboard__(),
    U = __new_input_name_keyboard__(),
    V = __new_input_name_keyboard__(),
    W = __new_input_name_keyboard__(),
    X = __new_input_name_keyboard__(),
    Y = __new_input_name_keyboard__(),
    Z = __new_input_name_keyboard__(),
    LeftCurlyBracket = __new_input_name_keyboard__(),
    Pipe = __new_input_name_keyboard__(),
    RightCurlyBracket = __new_input_name_keyboard__(),
    Tilde = __new_input_name_keyboard__(),
    Delete = __new_input_name_keyboard__(),
    Keypad0 = __new_input_name_keyboard__(),
    Keypad1 = __new_input_name_keyboard__(),
    Keypad2 = __new_input_name_keyboard__(),
    Keypad3 = __new_input_name_keyboard__(),
    Keypad4 = __new_input_name_keyboard__(),
    Keypad5 = __new_input_name_keyboard__(),
    Keypad6 = __new_input_name_keyboard__(),
    Keypad7 = __new_input_name_keyboard__(),
    Keypad8 = __new_input_name_keyboard__(),
    Keypad9 = __new_input_name_keyboard__(),
    KeypadPeriod = __new_input_name_keyboard__(),
    KeypadDivide = __new_input_name_keyboard__(),
    KeypadMultiply = __new_input_name_keyboard__(),
    KeypadMinus = __new_input_name_keyboard__(),
    KeypadPlus = __new_input_name_keyboard__(),
    KeypadEnter = __new_input_name_keyboard__(),
    KeypadEquals = __new_input_name_keyboard__(),
    Insert = __new_input_name_keyboard__(),
    Home = __new_input_name_keyboard__(),
    End = __new_input_name_keyboard__(),
    PageUp = __new_input_name_keyboard__(),
    PageDown = __new_input_name_keyboard__(),
    F1 = __new_input_name_keyboard__(),
    F2 = __new_input_name_keyboard__(),
    F3 = __new_input_name_keyboard__(),
    F4 = __new_input_name_keyboard__(),
    F5 = __new_input_name_keyboard__(),
    F6 = __new_input_name_keyboard__(),
    F7 = __new_input_name_keyboard__(),
    F8 = __new_input_name_keyboard__(),
    F9 = __new_input_name_keyboard__(),
    F10 = __new_input_name_keyboard__(),
    F11 = __new_input_name_keyboard__(),
    F12 = __new_input_name_keyboard__(),
    F13 = __new_input_name_keyboard__(),
    F14 = __new_input_name_keyboard__(),
    F15 = __new_input_name_keyboard__(),
    Numlock = __new_input_name_keyboard__(),
    CapsLock = __new_input_name_keyboard__(),
    ScrollLock = __new_input_name_keyboard__(),
    RightShift = __new_input_name_keyboard__(),
    LeftShift = __new_input_name_keyboard__(),
    RightControl = __new_input_name_keyboard__(),
    LeftControl = __new_input_name_keyboard__(),
    RightAlt = __new_input_name_keyboard__(),
    LeftAlt = __new_input_name_keyboard__(),
    RightCommand = __new_input_name_keyboard__(),
    LeftCommand = __new_input_name_keyboard__(),
    AltGr = __new_input_name_keyboard__(),
    Help = __new_input_name_keyboard__(),
    Print = __new_input_name_keyboard__(),
    SysReq = __new_input_name_keyboard__(),
    Break = __new_input_name_keyboard__(),
    Menu = __new_input_name_keyboard__(),
}
